### ISSUE TITLE
Remove ch.idsia.crema.model.graphica.Graph

### ISSUE THREAD

**Issue by davidhuber** [IDSIA/crema#40]
We should remove ch.idsia.crema.model.graphica.Graph and use the JGraphT::graph instead. With this change we will also get rid of the h.idsia.crema.model.graphica.SparseList

This WILL slightly impact credici as the getVariables methods will not be available anymore and will have to be replaced with calls to vertexSet and the JGraphT methods

**Comment by cbonesana** [comment]
I created the branch [dev-features-model-class-hierarchy](https://github.com/IDSIA/crema/tree/dev-features-model-class-hierarchy) for this issue.

Currently class `GenericSparseModel` has an issue with the [convert](https://github.com/IDSIA/crema/blob/2458feed808bf716acfac5879745d3b83d0deada/src/main/java/ch/idsia/crema/model/graphical/GenericSparseModel.java#L96) method: we can't copy a JGrapht Graph without knowing its implementation.

Another issue is related to the similarities between many methods of class `SparseDirectedAcyclicGraph` and `GenericSparseModel`. Maybe consider a composition or an aggregation of the two?

**Comment by cbonesana** [comment]
Updated the [dev-features-model-class-hierarchy](https://github.com/IDSIA/crema/tree/dev-features-model-class-hierarchy) branch with the new class hierarchy and some major refactoring of the library.

More test needed.

**Comment by cbonesana** [comment]
Issue solved by #42 .
